language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILDSYSTEM=cmake
  - BUILDSYSTEM=autotools

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp-dev
      - libboost-dev
      - autoconf
      - automake
      - libtool

script: ./.travis-build.sh
