language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILDSYSTEM=cmake
  - BUILDSYSTEM=cmake-scip
  - BUILDSYSTEM=cmake-scip SCIPOPTSUITE_VERSION=3.2.0
  - BUILDSYSTEM=cmake-nmzintegrate
  - BUILDSYSTEM=autotools
  - BUILDSSYTEM=autotools CONFIGURE_FLAGS="--disable-openmp"
  - BUILDSYSTEM=autotools-makedistcheck
  - BUILDSYSTEM=autotools-makedistcheck-nmzintegrate
  - BUILDSYSTEM=autotools-scip
  - BUILDSYSTEM=autotools-scip SCIPOPTSUITE_VERSION=3.2.0
  - BUILDSYSTEM=classic
  - BUILDSYSTEM=classic-scip

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: BUILDSYSTEM=cmake-nmzintegrate
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: BUILDSYSTEM=autotools-nmzintegrate
    - os: osx
      osx_image: xcode8.2
      compiler: gcc
      env: BUILDSYSTEM=autotools-nmzintegrate
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: BUILDSYSTEM=autotools-makedistcheck-nmzintegrate
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: BUILDSYSTEM=autotools-scip
    - os: osx
      osx_image: xcode8.1
      compiler: clang
      env: BUILDSYSTEM=autotools-makedistcheck-nmzintegrate
    - os: osx
      osx_image: xcode8.1
      compiler: clang
      env: BUILDSYSTEM=autotools-scip
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: BUILDSYSTEM=autotools-makedistcheck-nmzintegrate
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: BUILDSYSTEM=autotools-scip
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILDSYSTEM=autotools-makedistcheck-nmzintegrate
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILDSYSTEM=autotools-scip
    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env: BUILDSYSTEM=autotools-makedistcheck-nmzintegrate
    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env: BUILDSYSTEM=autotools-scip
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: BUILDSYSTEM=autotools-makedistcheck-nmzintegrate
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: BUILDSYSTEM=autotools-scip
      

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp-dev
      - libboost-dev
      - autoconf
      - automake
      - libtool
      - time

script: ./.travis-build.sh
