language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILDSYSTEM=cmake
  - BUILDSYSTEM=autotools
  - BUILDSYSTEM=autotools-makedistcheck
  - BUILDSYSTEM=autotools-makedistcheck-nmzintegrate
  - BUILDSYSTEM=autotools-scip
  - BUILDSYSTEM=autotools-scip SCIPOPTSUITE_VERSION=3.2.0
  - BUILDSYSTEM=classic
  - BUILDSYSTEM=classic-scip

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp-dev
      - libboost-dev
      - autoconf
      - automake
      - libtool

script: ./.travis-build.sh
