language: cpp
compiler:
  - gcc
  - clang

env:
  - BUILDSYSTEM=cmake
  - BUILDSYSTEM=autotools

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp-dev
      - libboost-dev

script: ./.travis-build.sh
