language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install autoconf automake libtool

compiler:
  - gcc
  - clang

env:
  - BUILDSYSTEM=cmake
  - BUILDSYSTEM=autotools

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp-dev
      - libboost-dev

script: ./.travis-build.sh
